version: '3.9'
services:
  web:
    build: .
    container_name: 'mfe-learner-app'
    image: mfe/app-learner
    ports:
      - '8081:8734'
    environment:
      - DOJO_BASE_URL=test.url
    networks:
      - mfe

networks:
  mfe:
    name: mfe
